
export enum UserState {
  LOGGED_IN = 'LOGGED_IN',
  LOGGED_OUT = 'LOGGED_OUT',
  NOT_SIGNED_UP = 'NOT_SIGNED_UP',
  SIGNED_UP_NOT_CONFIRMED = 'SIGNED_UP_NOT_CONFIRMED'
}

export enum PairingState {
  NOT_PAIRED = 'NOT_PAIRED',
  PAIRED = 'PAIRED',
}
